import React from 'react';
import configureStore from './store';
import * as actions from './actions';

class Apply extends React.Component{
	componentDidMount(){
		this.unsubscribe = this.store.subscribe(() => {
			this.setState(this.store.getState())
		});
	}
	componentWillUnmount(){
		this.unsubscribe();
	}

	constructor(props){
		super(props);
		this.store = configureStore();
		this.state = this.store.getState();
	}

	render(){
		return(
		  <div>
			<h1 style={{color:this.state.color,backgroundColor:this.state.bgcolor}}>Hello This is generated by Apply</h1>
			<img src={this.state.src} ></img>
		  </div>	
		)
	}
}

export default Apply;